# Usa la imagen oficial de nginx como base
FROM nginx:latest

# Copia el archivo index.html en el contenedor, en el directorio de nginx
COPY index.html /usr/share/nginx/html/index.html

# Expone el puerto 80 (puerto por defecto de nginx)
EXPOSE 80



